import '/flutter_flow/flutter_flow_icon_button.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import 'package:flutter/material.dart';
import 'package:flutter_markdown_plus/flutter_markdown_plus.dart';
import 'term_model.dart';
export 'term_model.dart';

class TermWidget extends StatefulWidget {
  const TermWidget({super.key});

  static String routeName = 'term';
  static String routePath = '/term';

  @override
  State<TermWidget> createState() => _TermWidgetState();
}

class _TermWidgetState extends State<TermWidget> {
  late TermModel _model;

  final scaffoldKey = GlobalKey<ScaffoldState>();

  @override
  void initState() {
    super.initState();
    _model = createModel(context, () => TermModel());

    WidgetsBinding.instance.addPostFrameCallback((_) => safeSetState(() {}));
  }

  @override
  void dispose() {
    _model.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        FocusScope.of(context).unfocus();
        FocusManager.instance.primaryFocus?.unfocus();
      },
      child: Scaffold(
        key: scaffoldKey,
        backgroundColor: Color(0xFFF2F2F7),
        body: Column(
          mainAxisSize: MainAxisSize.max,
          children: [
            Expanded(
              child: Stack(
                children: [
                  Align(
                    alignment: AlignmentDirectional(0.0, 0.0),
                    child: Container(
                      constraints: BoxConstraints(
                        maxWidth: 600.0,
                      ),
                      decoration: BoxDecoration(),
                      child: Padding(
                        padding: EdgeInsetsDirectional.fromSTEB(
                            16.0, 0.0, 16.0, 0.0),
                        child: SingleChildScrollView(
                          primary: false,
                          child: Column(
                            mainAxisSize: MainAxisSize.max,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              MarkdownBody(
                                data:
                                    '''# **TERMS OF USE & END USER LICENSE AGREEMENT (EULA) – ROAST NUTRITRACKER**\n\n**Last updated:** 19 April 2026\n\n**Effective date:** 22 November 2025\n\nWelcome to **Roast NutriTracker** (“**App**”, “**we**”, “**us**”, “**our**”). By downloading, accessing, or using the App, you agree to these **Terms of Use & EULA** (“**Terms**”). If you do not agree, do not use the App.\n\n---\n\n## **1) Acknowledgement (Apple / App Store Users)**\n\nThese Terms are an agreement between **you** and the **App provider** (Roast NutriTracker), not with Apple. Apple is not responsible for the App or its content. If you obtained the App from the Apple App Store, your use must also comply with Apple’s applicable terms and policies.\n\n---\n\n## **2) Definitions**\n\n- **“User Content”** means any photos, images, text, audio, or other content you submit to the App.\n- **“AI Output”** means any text, audio, or other output generated by the App using AI.\n- **“Services”** means the App and related features, including subscriptions and content.\n\n---\n\n## **3) Purpose of the App (Entertainment + General Information)**\n\nRoast NutriTracker provides **nutrition insights, entertainment, and satirical, comedic, and fictional commentary**, including the ability to generate humorous or “roast-style” content based on user-submitted images (which may include food, objects, or people).\n\nThe App is **not** a medical device and is **not** intended to provide medical, dietary, fitness, or professional advice.\n\nThe App may use third-party AI services (for example, text generation and/or audio generation). You understand that AI Output:\n\n- may be **inaccurate**, incomplete, or inappropriate,\n- may be **estimates** (especially for calories/macros),\n- is provided for **entertainment and general informational purposes** only.\n\n---\n\n## **4) Important Disclaimers (Read Carefully)**\n\n### **4.1 No Medical Advice**\n\nAny nutritional estimates, calorie breakdowns, “recommendations”, or commentary are **not medical advice**. Always consult a qualified professional before making major dietary or health changes.\n\n### **4.2 AI Limitations & User Responsibility**\n\nYou are responsible for how you use the App and AI Output. Do not rely on the App for decisions that could cause harm (health, safety, legal, financial, etc.).\n\nYou agree that you **will not rely on any AI Output as a substitute for professional advice or as a basis for any decisions that may result in harm**, and you use all outputs at your own risk.\n\n### **4.3 Satire / Roast Disclaimer**\n\nThe App contains **humor, parody, and satire**. Any “roasting” is a creative performance based on user-submitted content (which may include food, objects, or people) and is not a statement of fact. If you don’t want humorous or spicy commentary, do not use roast features.\n\n### **4.4 Not Directed at You / No Personal Targeting**\n\nThe App’s roasts, jokes, and satirical commentary are **fictional, generalized comedic content** generated in response to user-submitted content and are intended for entertainment. They are **not statements of fact** and are **not intended to target, harass, or harm you personally or any identifiable individual, even if the output appears to reference or resemble a real person**. If you feel offended or uncomfortable with the humor or tone, you should stop using roast features or stop using the App. This includes situations where you upload images of yourself; any generated content remains fictional, AI-generated, and for entertainment purposes only. If you upload images of other individuals, you are responsible for ensuring you have the right to do so and for how such content is used within the App.\n\n---\n\n## **5) License Grant (Your Right to Use the App)**\n\nSubject to these Terms, we grant you a **limited, personal, non-exclusive, non-transferable, revocable** license to download and use the App on devices you own or control, for **personal, non-commercial** use.\n\nYou may not:\n\n- copy, modify, reverse engineer, decompile, or attempt to extract source code (except where the law allows despite this restriction),\n- resell, rent, sublicense, or distribute the App,\n- use the App to violate any law or third-party rights,\n- bypass, disable, or interfere with security, rate limits, or access controls.\n\n---\n\n## **6) Accounts & Security**\n\nIf the App offers accounts, you agree:\n\n- not to impersonate others or misrepresent your identity,\n- to keep your login credentials confidential,\n- you are responsible for activity on your account, unless caused by our breach.\n\nWe may suspend or terminate accounts for violations or security risks.\n\n---\n\n## **7) User Content (Ownership, License, and Rules)**\n\n### **7.1 Your Ownership**\n\nYou retain ownership of your User Content.\n\n### **7.2 Limited License to Operate the App**\n\nYou grant us a worldwide, non-exclusive, royalty-free license to **host, store, process, reproduce, and display** your User Content **only as needed to operate and improve the App**, and to ensure safety, moderation, and abuse prevention, including:\n\n- generating AI Output based on your input,\n- showing your content to you (and only to others when you choose to share),\n- providing customer support and troubleshooting,\n- preventing abuse, enforcing Terms, and complying with law.\n\n**Marketing / promotion:** We will not use your User Content for marketing or public promotion **without your explicit permission** (for example, an opt-in consent).\n\n### **7.3 Your Promises About User Content**\n\nYou represent that you have the rights to submit User Content and that it does not:\n\n- infringe copyrights, trademarks, privacy/publicity rights, or other rights,\n- contain illegal content (including child sexual abuse material),\n- include images of identifiable individuals without their consent where required by applicable law, and **you are solely responsible for obtaining any necessary permissions, and for any claims, damages, or liabilities arising from such content.**\n- include sensitive personal data you don’t have the right to share,\n- violate these Terms,\n- give rise to claims related to privacy, publicity rights, defamation, or emotional distress.\n\nWe may remove or restrict User Content at our discretion, including to comply with law or safety.\n\n---\n\n## **8) Prohibited Uses (Content + Safety)**\n\nThe App allows humorous, lighthearted, and non-targeted comedic use (“roasting”), but not abusive or harmful content. You agree not to use the App to generate, request, upload, or distribute content that is:\n\n- illegal, sexually exploitative (especially involving minors), or promotes self-harm,\n- hateful, harassing, threatening, or targeted abuse,\n- deceptive or fraudulent (scams, impersonation to mislead, etc.),\n- uploading or using images of other individuals for the purpose of generating abusive, harassing, or humiliating content,\n- instructions for wrongdoing, violence, or illegal activity.\n\n### **8.1 Impersonation & Voice/Celebrity Requests (Important)**\n\nYou must not use the App to:\n\n- imitate or replicate a real person’s voice or identity in a deceptive or harmful way,\n- claim AI Output is a real person speaking (unless clearly disclosed),\n- request or generate content intended to mislead others into believing it is a real individual or endorsement.\n\nWe may restrict prompts, block outputs, or suspend accounts for violations.\n\n### **8.2 No Targeted Harassment**\n\nYou must not use the App to target, harass, defame, or generate abusive or degrading content about a specific identifiable individual or protected group, including by uploading their image. The App is intended for generalized, non-targeted comedic use, not for personal attacks. We may restrict prompts, remove content, or suspend access for violations. We reserve the right to determine what constitutes a violation at our sole discretion.\n\n---\n\n## **9) In-App Reporting / Flagging of Offensive AI Content**\n\nThe App may provide tools to **report or flag offensive AI Output or User Content**. You can also report by emailing: [**nutritrackerrr@gmail.com**](mailto:nutritrackerrr@gmail.com).\n\nWe review reports and may remove content, restrict features, or suspend accounts as appropriate.\n\n---\n\n## **10) Intellectual Property**\n\nThe App (including code, design, UI, branding, and our original content) is owned by Roast NutriTracker and/or licensors and is protected by applicable laws.\n\nYou may not use our name, logo, or branding without permission.\n\n### **10.1 Parody / Satire Note**\n\nThe App may include satirical or parody personas and comedic styles. Nothing in the App should be interpreted as endorsement by any third party.\n\n---\n\n## **11) Copyright Complaints / Takedowns**\n\nIf you believe content in the App infringes your copyright, send a notice to [**nutritrackerrr@gmail.com**](mailto:nutritrackerrr@gmail.com) with:\n\n- your name and contact info,\n- identification of the work claimed infringed,\n- where the allegedly infringing content appears,\n- a good-faith statement and confirmation you are the rights holder or authorized agent.\n\nWe may remove allegedly infringing material and may terminate repeat infringers where appropriate.\n\n---\n\n## **12) Third-Party Services**\n\nThe App may integrate third-party services (including AI providers). Third-party services are governed by their own terms and policies. We do not control them and are not responsible for third-party outages or changes.\n\n---\n\n## **13) Payments, Subscriptions, Renewals, and Refunds**\n\nSome features may require payment (subscriptions or one-time purchases).\n\n### **13.1 App Store / Google Play Billing**\n\nIf you purchase through Apple App Store or Google Play:\n\n- billing, renewals, cancellations, and refunds are handled by the store and subject to the store’s terms,\n- subscriptions typically **auto-renew** unless cancelled,\n- you can manage or cancel in your store account settings.\n\n### **13.2 No Store-Bypass**\n\nIf a purchase is processed by the store, we generally cannot issue refunds directly (the store controls it). For help, contact the store provider first. You can also contact us at [**nutritrackerrr@gmail.com**](mailto:nutritrackerrr@gmail.com) for assistance.\n\n---\n\n## **14) Privacy**\n\nYour use of the App is also governed by our **Privacy Policy**, which describes what data we collect and how we use it. If these Terms conflict with the Privacy Policy regarding privacy topics, the Privacy Policy controls.\n\n### **14.1 Data Retention & Deletion Requests**\n\nYou may request deletion of your account and associated data as described in the Privacy Policy or by contacting [**nutritrackerrr@gmail.com**](mailto:nutritrackerrr@gmail.com). Some data may be retained where required by law, security, or legitimate operational needs (for example, backups for a limited time).\n\n---\n\n## **15) Termination**\n\nWe may suspend or terminate your access to the App at any time, **with or without cause, without prior notice and without liability to you**, including if you:\n\n- violate these Terms,\n- create risk or possible legal exposure for us or others,\n- misuse the App or attempt to bypass safeguards.\n\nYou may stop using the App at any time. \n\n---\n\n## **16) Warranty Disclaimer**\n\nTHE APP AND ALL CONTENT/AI OUTPUT ARE PROVIDED **“AS IS”** AND **“AS AVAILABLE.”**\n\nTO THE MAXIMUM EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABILITY, AND NON-INFRINGEMENT. WE DO NOT GUARANTEE THAT THE APP WILL BE ERROR-FREE, UNINTERRUPTED, OR THAT OUTPUTS WILL BE ACCURATE OR SAFE FOR ANY PARTICULAR USE.\n\n---\n\n## **17) Limitation of Liability**\n\nTO THE MAXIMUM EXTENT PERMITTED BY LAW, ROAST NUTRITRACKER AND ITS DEVELOPERS/AFFILIATES/LICENSORS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, OR GOODWILL, ARISING FROM OR RELATED TO:\n\n- YOUR USE OF (OR INABILITY TO USE) THE APP,\n- RELIANCE ON NUTRITION ESTIMATES OR AI OUTPUT,\n- OFFENSE TAKEN OR EMOTIONAL DISTRESS FROM SATIRICAL CONTENT,\n- **ANY CLAIMS BASED ON DEFAMATION, EMOTIONAL HARM, OR REPUTATIONAL HARM ALLEGING THAT SATIRICAL OUTPUT WAS “ABOUT” YOU OR ANY THIRD PARTY, TO THE EXTENT THE OUTPUT IS PRESENTED AS HUMOR/PARODY AND NOT AS VERIFIED FACT.**\n- USER CONTENT OR THIRD-PARTY SERVICES,\n- **ANY CLAIMS ARISING FROM USER USE OF THE APP TO GENERATE OR SHARE CONTENT INVOLVING THIRD PARTIES (INCLUDING PHOTOS OF INDIVIDUALS),**\n- ANY MISUSE OF THE APP BY USERS, INCLUDING USE INVOLVING THIRD PARTIES OR USER-GENERATED CONTENT,\n\nIN ALL CASES, OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID FOR THE APP IN THE **12 MONTHS** BEFORE THE EVENT GIVING RISE TO THE CLAIM (OR **€10** IF YOU PAID NOTHING), UNLESS LAW REQUIRES OTHERWISE.\n\nYOU AGREE THAT THE APP FUNCTIONS AS A TOOL BASED ON USER INPUT, AND THAT ANY OUTPUT IS GENERATED AUTOMATICALLY WITHOUT HUMAN REVIEW.\n\nSome jurisdictions do not allow certain limitations, so some of the above may not apply to you.\n\n---\n\n## **18) Indemnification**\n\nYou agree to indemnify and hold harmless Roast NutriTracker from claims, damages, liabilities, and expenses (including reasonable legal fees) arising from:\n\n- your use of the App,\n- your User Content,\n- your violation of these Terms or any law,\n- your violation of third-party rights.\n\n---\n\n## **19) Governing Law & Disputes**\n\nThese Terms are governed by the laws of the **Netherlands**, excluding conflict-of-laws rules.\n\nCourts located in **the Netherlands** will have jurisdiction.\n\n**EEA/UK consumer rights:** If you live in the EEA or UK, nothing in these Terms limits your mandatory consumer rights under the laws of your country of residence.\n\n---\n\n## **20) Changes to These Terms**\n\nWe may update these Terms from time to time. If changes are material, we may provide notice in the App or by other reasonable means. Continued use after changes become effective means you accept the updated Terms.\n\n---\n\n## **21) Contact**\n\nQuestions, support, legal notices, and copyright complaints:\n\n[**nutritrackerrr@gmail.com**](mailto:nutritrackerrr@gmail.com)\n\nRoast NutriTracker is an independent project provided by a private individual.\n\n---''',
                                selectable: true,
                                onTapLink: (_, url, __) => launchURL(url!),
                              ),
                            ]
                                .addToStart(SizedBox(height: 125.0))
                                .addToEnd(SizedBox(height: 100.0)),
                          ),
                        ),
                      ),
                    ),
                  ),
                  Container(
                    decoration: BoxDecoration(
                      gradient: LinearGradient(
                        colors: [
                          FlutterFlowTheme.of(context).secondaryBackground,
                          Color(0xF2F2F2F7),
                          Color(0x00F2F2F7)
                        ],
                        stops: [0.0, 0.8, 1.0],
                        begin: AlignmentDirectional(0.0, -1.0),
                        end: AlignmentDirectional(0, 1.0),
                      ),
                    ),
                    child: Padding(
                      padding: EdgeInsetsDirectional.fromSTEB(
                          12.0, 55.0, 12.0, 12.0),
                      child: Row(
                        mainAxisSize: MainAxisSize.max,
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Container(
                            width: 45.0,
                            height: 45.0,
                            decoration: BoxDecoration(
                              boxShadow: [
                                BoxShadow(
                                  blurRadius: 7.0,
                                  color: Color(0x0D2C2C2C),
                                  offset: Offset(
                                    0.0,
                                    2.0,
                                  ),
                                )
                              ],
                              shape: BoxShape.circle,
                            ),
                            child: FlutterFlowIconButton(
                              borderRadius: 70.0,
                              buttonSize: 45.0,
                              fillColor: Colors.white,
                              icon: Icon(
                                Icons.arrow_back_ios_rounded,
                                color: FlutterFlowTheme.of(context).primaryText,
                                size: 14.0,
                              ),
                              onPressed: () async {
                                context.safePop();
                              },
                            ),
                          ),
                          Text(
                            'TERMS OF USE (EULA)',
                            style: FlutterFlowTheme.of(context)
                                .bodyMedium
                                .override(
                                  fontFamily: 'SF Pro',
                                  fontSize: 18.0,
                                  letterSpacing: 0.0,
                                  fontWeight: FontWeight.w500,
                                ),
                          ),
                          Container(
                            width: 45.0,
                            height: 45.0,
                            decoration: BoxDecoration(
                              shape: BoxShape.circle,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
